PORT = 5001
DB_HOST = "localhost"
DB_PORT = "3306"
DB_NAME = "OnlinePayment"
DB_USERNAME = ""
DB_PASSWD = ""
SESSION_SECRET_KEY = ""
SQLALCHEMY_ECHO = True # SQLAlchemy 是否打 Log
FLASK_ENV = 'dev' # 'prod' | 'dev' | 'test' 
STATIC_DIRECTORY = 'static'